/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateRoomRequest = IDL.Record({
  'hostNickname' : IDL.Text,
  'roomCode' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const RoomState = IDL.Record({
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Text),
  'chatMessages' : IDL.Vec(ChatMessage),
  'lastUpdated' : Time,
  'hostNickname' : IDL.Text,
  'isPlaying' : IDL.Bool,
  'videoSource' : IDL.Text,
  'position' : IDL.Float64,
  'syncVersion' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([CreateRoomRequest], [], []),
  'deleteRoom' : IDL.Func([IDL.Text], [], []),
  'forceSyncAll' : IDL.Func(
      [
        IDL.Record({
          'isPlaying' : IDL.Bool,
          'position' : IDL.Float64,
          'roomCode' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllParticipants' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getAllRoomStates' : IDL.Func([], [IDL.Vec(RoomState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getRoomState' : IDL.Func([IDL.Text], [RoomState], ['query']),
  'getSyncVersion' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [RoomState], []),
  'leaveRoom' : IDL.Func(
      [IDL.Record({ 'nickname' : IDL.Text, 'roomCode' : IDL.Text })],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func(
      [
        IDL.Record({
          'nickname' : IDL.Text,
          'message' : IDL.Text,
          'roomCode' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'setVideoSource' : IDL.Func(
      [IDL.Record({ 'videoSource' : IDL.Text, 'roomCode' : IDL.Text })],
      [],
      [],
    ),
  'updatePlaybackState' : IDL.Func(
      [
        IDL.Record({
          'isPlaying' : IDL.Bool,
          'position' : IDL.Float64,
          'roomCode' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateRoomRequest = IDL.Record({
    'hostNickname' : IDL.Text,
    'roomCode' : IDL.Text,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const RoomState = IDL.Record({
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Text),
    'chatMessages' : IDL.Vec(ChatMessage),
    'lastUpdated' : Time,
    'hostNickname' : IDL.Text,
    'isPlaying' : IDL.Bool,
    'videoSource' : IDL.Text,
    'position' : IDL.Float64,
    'syncVersion' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([CreateRoomRequest], [], []),
    'deleteRoom' : IDL.Func([IDL.Text], [], []),
    'forceSyncAll' : IDL.Func(
        [
          IDL.Record({
            'isPlaying' : IDL.Bool,
            'position' : IDL.Float64,
            'roomCode' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllParticipants' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getAllRoomStates' : IDL.Func([], [IDL.Vec(RoomState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getRoomState' : IDL.Func([IDL.Text], [RoomState], ['query']),
    'getSyncVersion' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [RoomState], []),
    'leaveRoom' : IDL.Func(
        [IDL.Record({ 'nickname' : IDL.Text, 'roomCode' : IDL.Text })],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func(
        [
          IDL.Record({
            'nickname' : IDL.Text,
            'message' : IDL.Text,
            'roomCode' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'setVideoSource' : IDL.Func(
        [IDL.Record({ 'videoSource' : IDL.Text, 'roomCode' : IDL.Text })],
        [],
        [],
      ),
    'updatePlaybackState' : IDL.Func(
        [
          IDL.Record({
            'isPlaying' : IDL.Bool,
            'position' : IDL.Float64,
            'roomCode' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };